### ISSUE TITLE
How about Firebase Hosting emulator

### ISSUE THREAD

**Issue by ptedu3** [Meyclem/where-is-it#1]
Hey,
Did you happen to also try hosting emulator? Is there any specific reason why you decided to not use it?
I'm asking because I'm trying to use hosting but does not work properly. Just wanted to see if you had similar experience.

Thanks

**Comment by Meyclem** [comment]
Hi!

I did not try the hosting emulator since I'm using Next and Vercel.

I had a problem with the auth Emulator though and had to enable the functions emulator to make it work, even if i'm not using it. Maybe the hosting one need the same sort of shenanigans?
